### ISSUE TITLE
Add Monit logo to NAF app logo selection

### ISSUE THREAD

**Issue by AmarIyengar** [narmi/design_system#1000]
Monit would like to have their logo used on their app being built for First IB. Additionally, we're starting the discussions of a possible partnership agreement that could turn into a reseller agreement, so we want to be able to offer their own branding as a good partner.

The below attached image is what they'd like us to use

![Monit_Light_Blue](https://github.com/narmi/design_system/assets/32844102/6d4d6a1a-2faa-45aa-9fc1-8e23f90455c4)

**Comment by akdetrick** [comment]
### Why isn't this done yet?

This ticket is in a holding pattern because we don't want to make all users, in all products, for all FIs, to download extra logos for specific NAF apps. 

I've made a [proposal/RFC](https://www.notion.so/narmi/RFC-NAF-Icons-42bceb8d7b9d45dfa85405357b9c6ed1?pvs=4) to update the way we handle NAF logos, so it will be up to product to decide if/when/how we want to prioritize this.


### Can we just add it anyway?

Yes, but it will render a box or question mark on anyone using anything but the latest mobile version. It would be better to solve the actual problem so that this setting becomes self-sufficient and flexible [as proposed](https://www.notion.so/narmi/RFC-NAF-Icons-42bceb8d7b9d45dfa85405357b9c6ed1?pvs=4)

**Comment by akdetrick** [comment]
## Why am I closing this?

We recently used an NDS icon for the Zelle logo, but it violated the design guidelines due to color requirements. We ended up using SVG.

Let's avoid adding any third party logos to the existing NDS icon set and instead use SVGs.
