### ISSUE TITLE
Support NDS icons on mobile

### ISSUE THREAD

**Issue by kylekennedy6** [narmi/design_system#700]
Currently, we tend to use MaterialIcons for our mobile apps and NDS icons on web. Ideally, the same icon string could be used across mobile and web.

This would be useful for our promos (defined in`InstitutionPromoDataSetting`) and NAF apps (see `image` field on `OauthApplication`, where we define an image/icon as something like `AddBox` (Material) or `plus_square` (NDS)

**Comment by wrbrand** [comment]
Bumping this to 2022.6-4 since it's not likely to be handled before our onsite.

**Comment by akdetrick** [comment]
# Context

Atlas uses its own **icomoon project** (with its own `selection.json`). From this config file, we use `createIconSetFromIcomoon` to generate an SVG icon set:
https://github.com/narmi/banking/blob/main/atlas/assets/fonts/icomoon.js

This set of SVG icons is consumed by importing `icomoon.js` as the `Icomoon` component, where we can render an SVG shape by name:

```jsx
<Icomoon name="narmi-bill" />
```

## Problems with this setup

Because web and mobile use separate icomoon projects, the icon names get out of sync, making it difficult or impossible to have a field in institution settings for customizing an icon by name, as there's no guarantee it will be the same on web and mobile.

To date, we have mapped the names to work around the problem, but this is not a good long-term solution.

## Proposed solution

Instead of using a separate icomoon project for mobile, atlas should install NDS as a dependency and import the selection.json directly from NDS when building the SVG icon set:

```diff
import { createIconSetFromIcoMoon } from "react-native-vector-icons";

-import icoMoonConfig from "./selection.json";
+import icoMoonConfig from "@narmi/design_system/dist/icons/selection.json";

export default createIconSetFromIcoMoon(
  icoMoonConfig,
  "icomoon",
  "icomoon.ttf"
);
```

## Next steps

- [ ] Audit the shapes and names in mobile. Document name changes and missing coverage for migrating to NDS icons
- [ ] Add any missing mobile icons to NDS
- [ ] Install NDS as a depdency in atlas and make code changes (including shape name changes in `Icomoon` component usage)

**Comment by akdetrick** [comment]
will likely need assistance with a data fix (and/or mapping old names to new ones programmatically): https://gist.github.com/akdetrick/c07d546df094f0716a2b5216281e4149
